#!/bin/sh

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo 'usage: ./run-tests [arg]'
  echo '    Run tests using the javascript interpreter $JS or d8.'
  echo '    If arg is present, compile before testing using'
  echo '    $CLOJURESCRIPT_HOME/bin/cljsc'
  exit 1
fi

[ "$PHANTOM_JS" ] || PHANTOM_JS=phantomjs

mkdir -p out
if [ "$1" ]; then
  ./compile || exit 1
fi

cp out/testall.js out/_testall.js
echo 'phantom.exit(0)' >> out/_testall.js

"$PHANTOM_JS" out/_testall.js
